### ISSUE TITLE
TypeError encounter

### ISSUE THREAD

**Issue by alexmasia** [nikensss/sauna#1]
I installed the package following the README guidelines and I encounter the this error when trying to apply sauna to finten

```console
sauna -p /Users/alexfaraday/repositories/finten
✔ outdated packages retrieved!
TypeError: Cannot read properties of undefined (reading 'split')
    at new Version (file:///Users/aencalado/repositories/sauna/dist/Version.js:4:46)
    at new Package (file:///Users/aencalado/repositories/sauna/dist/Package.js:12:31)
    at file:///Users/aencalado/repositories/sauna/dist/index.js:17:32
    at Array.map (<anonymous>)
    at file:///Users/aencalado/repositories/sauna/dist/index.js:17:10
    at Generator.next (<anonymous>)
    at fulfilled (file:///Users/aencalado/repositories/sauna/dist/index.js:5:58)
```

**Comment by nikensss** [comment]
Thanks for opening an issue. Could you show me the output of `npm outdated --json` when you run it on this folder: `/Users/alexfaraday/repositories/finten`?

**Comment by alexmasia** [comment]
here you have

```json
{
  "@google-cloud/recaptcha-enterprise": {
    "wanted": "2.5.0",
    "latest": "2.5.0",
    "dependent": "finten"
  },
  "axios": {
    "wanted": "0.21.4",
    "latest": "0.27.2",
    "dependent": "finten"
  },
  "bcryptjs": {
    "wanted": "2.4.3",
    "latest": "2.4.3",
    "dependent": "finten"
  },
  "chalk": {
    "wanted": "4.1.2",
    "latest": "5.0.1",
    "dependent": "finten"
  },
  "cors": {
    "wanted": "2.8.5",
    "latest": "2.8.5",
    "dependent": "finten"
  },
  "csv-parser": {
    "wanted": "2.3.5",
    "latest": "3.0.0",
    "dependent": "finten"
  },
  "dotenv": {
    "wanted": "8.6.0",
    "latest": "16.0.0",
    "dependent": "finten"
  },
  "express": {
    "wanted": "4.18.0",
    "latest": "4.18.0",
    "dependent": "finten"
  },
  "jsonwebtoken": {
    "wanted": "8.5.1",
    "latest": "8.5.1",
    "dependent": "finten"
  },
  "moment": {
    "wanted": "2.29.3",
    "latest": "2.29.3",
    "dependent": "finten"
  },
  "mongoose": {
    "wanted": "5.13.14",
    "latest": "6.3.1",
    "dependent": "finten"
  },
  "nodemon": {
    "wanted": "2.0.15",
    "latest": "2.0.15",
    "dependent": "finten"
  },
  "ora": {
    "wanted": "4.1.1",
    "latest": "6.1.0",
    "dependent": "finten"
  },
  "passport": {
    "wanted": "0.4.1",
    "latest": "0.5.2",
    "dependent": "finten"
  },
  "passport-jwt": {
    "wanted": "4.0.0",
    "latest": "4.0.0",
    "dependent": "finten"
  },
  "supertest": {
    "wanted": "4.0.2",
    "latest": "6.2.3",
    "dependent": "finten"
  },
  "ts-node": {
    "wanted": "8.10.2",
    "latest": "10.7.0",
    "dependent": "finten"
  },
  "typescript": {
    "wanted": "4.6.3",
    "latest": "4.6.3",
    "dependent": "finten"
  },
  "validator": {
    "wanted": "13.7.0",
    "latest": "13.7.0",
    "dependent": "finten"
  }
}
```

**Comment by nikensss** [comment]
I think you should update your version of `npm`. I am going to add a check to make sure no Error is thrown. Could you tell me what do you get when you run `npm --version`?

**Comment by alexmasia** [comment]
its version 8.6.0

**Comment by nikensss** [comment]
Ok, can you show me the output of `npm outdated --json --long` on that same location?

**Comment by alexmasia** [comment]
```json
{
  "@commitlint/cli": {
    "current": "16.2.3",
    "wanted": "16.2.3",
    "latest": "16.2.4",
    "dependent": "sauna",
    "location": "/Users/aencalado/repositories/sauna/node_modules/@commitlint/cli",
    "type": "devDependencies",
    "homepage": "https://commitlint.js.org/"
  },
  "@commitlint/config-conventional": {
    "current": "16.2.1",
    "wanted": "16.2.1",
    "latest": "16.2.4",
    "dependent": "sauna",
    "location": "/Users/aencalado/repositories/sauna/node_modules/@commitlint/config-conventional",
    "type": "devDependencies",
    "homepage": "https://commitlint.js.org/"
  },
  "@typescript-eslint/eslint-plugin": {
    "current": "5.20.0",
    "wanted": "5.20.0",
    "latest": "5.21.0",
    "dependent": "sauna",
    "location": "/Users/aencalado/repositories/sauna/node_modules/@typescript-eslint/eslint-plugin",
    "type": "devDependencies",
    "homepage": "https://github.com/typescript-eslint/typescript-eslint#readme"
  },
  "@typescript-eslint/parser": {
    "current": "5.20.0",
    "wanted": "5.20.0",
    "latest": "5.21.0",
    "dependent": "sauna",
    "location": "/Users/aencalado/repositories/sauna/node_modules/@typescript-eslint/parser",
    "type": "devDependencies",
    "homepage": "https://github.com/typescript-eslint/typescript-eslint#readme"
  }
}
```

**Comment by nikensss** [comment]
Could you try with the latest version?

**Comment by nikensss** [comment]
Dependencies needed to be installed
